apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: podname
  name: podname
spec:
  containers:
  - image: quay.io/mayank123modi/myapache
    name: podname
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
