apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mayank
  name: mayank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mayank
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mayank
    spec:
      containers:
      - image: quay.io/mayank123modi/myapache
        name: myapache
        resources: 
          requests: 
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 800m
            memory: 900Mi
status: {}
