apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mysql1
  name: cmmysql1
spec:
  containers:
  - envFrom:
    - configMapRef: 
        name: mayank
    image: quay.io/mayank123modi/mysql
    name: mysql1
