apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "resource-limits"
spec:
  limits:
    - type: "Container"
      max:
        cpu: "2"
        memory: "1Gi"
      min:
        cpu: "100m"
        memory: "4Mi"
    - type: "Pod"
      max:
        cpu: "3"
        memory: "2Gi"
      min:
        cpu: "110m"
        memory: "6Mi"
